
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web_psql


test:
  <<: *default
  database: web_psql

production:
  <<: *default
  database: web_production
  username: web
  password: <%= ENV["WEB_DATABASE_PASSWORD"] %>
